export const BUG_CREATE_REQUEST = "BUG_CREATE_REQUEST";
export const BUG_CREATE_SUCCESS = "BUG_CREATE_SUCCESS";
export const BUG_CREATE_FAIL = "BUG_CREATE_FAIL";

export const BUG_DETAILS_REQUEST = "BUG_DETAILS_REQUEST";
export const BUG_DETAILS_SUCCESS = "BUG_DETAILS_SUCCESS";
export const BUG_DETAILS_FAIL = "BUG_DETAILS_FAIL";

export const BUG_ALLOCATED_REQUEST = "BUG_ALLOCATED_REQUEST";
export const BUG_ALLOCATED_SUCCESS = "BUG_ALLOCATED_SUCCESS";
export const BUG_ALLOCATED_FAIL = "BUG_ALLOCATED_FAIL";
export const BUG_ALLOCATED_RESET = "BUG_ALLOCATED_RESET";

export const BUG_LIST_MY_REQUEST = "BUG_LIST_MY_REQUEST";
export const BUG_LIST_MY_SUCCESS = "BUG_LIST_MY_SUCCESS";
export const BUG_LIST_MY_FAIL = "BUG_LIST_MY_FAIL";
export const BUG_LIST_MY_RESET = "BUG_LIST_MY_RESET";

export const BUG_LIST_REQUEST = "BUG_LIST_REQUEST";
export const BUG_LIST_SUCCESS = "BUG_LIST_SUCCESS";
export const BUG_LIST_FAIL = "BUG_LIST_FAIL";

export const BUG_SOLVED_REQUEST = "BUG_SOLVED_REQUEST";
export const BUG_SOLVED_SUCCESS = "BUG_SOLVED_SUCCESS";
export const BUG_SOLVED_FAIL = "BUG_SOLVED_FAIL";
export const BUG_SOLVED_RESET = "BUG_SOLVED_RESET";
